Repository depromeet/sulsul-BE, pull requests merged in 2022-05, with the labels that each got.

#22 [개발] Review 관련 CUD v1 수정
  src/main/java/com/depromeet/sulsul/domain/review/controller/ReviewController.java
  src/main/java/com/depromeet/sulsul/domain/review/dto/ReviewDto.java
  src/main/java/com/depromeet/sulsul/domain/review/dto/ReviewRequest.java
  src/main/java/com/depromeet/sulsul/domain/review/dto/ReviewUpdateRequest.java
  src/main/java/com/depromeet/sulsul/domain/review/entity/Review.java
  src/main/java/com/depromeet/sulsul/domain/review/repository/ReviewRepository.java
  src/main/java/com/depromeet/sulsul/domain/review/service/ReviewService.java
Labels: chore, request a review

#17 ✨ 도커 이미지 CI 구현
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
Labels: chore, test, request a review

#26 :green_heart: CI 빌드 수정
  Dockerfile
Labels: bug

#27 🎨 Record + Record Flavor 조회 및 저장기능 추가
  src/main/java/com/depromeet/sulsul/domain/beerFlavor/dto/BeerFlavorRecordDto.java
  src/main/java/com/depromeet/sulsul/domain/beerFlavor/dto/BeerFlavorRequest.java
  src/main/java/com/depromeet/sulsul/domain/beerFlavor/repository/BeerFlavorRepository.java
  src/main/java/com/depromeet/sulsul/domain/beerFlavor/service/BeerFlavorService.java
  src/main/java/com/depromeet/sulsul/domain/flavor/dto/FlavorDto.java
  src/main/java/com/depromeet/sulsul/domain/flavor/entity/Flavor.java
  src/main/java/com/depromeet/sulsul/domain/flavor/repository/FlavorRepository.java
  src/main/java/com/depromeet/sulsul/domain/member/dto/MemberRecordDto.java
  src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordDto.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordRequest.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordUpdateRequest.java
  src/main/java/com/depromeet/sulsul/domain/record/entity/Record.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepository.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/record/service/RecordService.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/dto/RecordFlavorDto.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/entity/RecordFlavor.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/repository/RecordFlavorRepository.java
  src/main/resources/application.yml
Labels: feat, chore, request a review

#47 ✨ 맥주 찜/취소 기능 추가 #45
  .github/workflows/gradle.yml
  .gitmodules
  Dockerfile
  src/main/java/com/depromeet/sulsul/common/entity/BaseEntity.java
  src/main/java/com/depromeet/sulsul/domain/MemberBeer.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerDetailResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/controller/MemberBeerController.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/entity/MemberBeer.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/repository/MemberBeerRepository.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/service/MemberBeerService.java
Labels: feat, chore, request a review

#48 :sparkles: Beer 검색 결과 개수 조회 API 개발
  src/main/java/com/depromeet/sulsul/common/external/AwsS3ImageClient.java
  src/main/java/com/depromeet/sulsul/common/response/dto/PageableResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/MemberBeer.java
  src/main/java/com/depromeet/sulsul/domain/beer/controller/BeerController.java
  src/main/java/com/depromeet/sulsul/domain/beer/controller/BeerControllerV2.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerCountResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerDetailResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerRequestDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerSearchConditionRequest.java
  src/main/java/com/depromeet/sulsul/domain/beer/entity/Beer.java
  src/main/java/com/depromeet/sulsul/domain/beer/entity/BeerType.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/beer/service/BeerService.java
  src/main/java/com/depromeet/sulsul/domain/beerFlavor/entity/BeerFlavor.java
  src/main/java/com/depromeet/sulsul/domain/continent/controller/ContinentController.java
  src/main/java/com/depromeet/sulsul/domain/continent/dto/ContinentDto.java
  src/main/java/com/depromeet/sulsul/domain/continent/entity/Continent.java
  src/main/java/com/depromeet/sulsul/domain/continent/service/ContinentService.java
  src/main/java/com/depromeet/sulsul/domain/country/controller/CountryController.java
  src/main/java/com/depromeet/sulsul/domain/country/dto/CountryDetail.java
  src/main/java/com/depromeet/sulsul/domain/country/entity/Country.java
  src/main/java/com/depromeet/sulsul/domain/country/repository/CountryRepository.java
  src/main/java/com/depromeet/sulsul/domain/country/service/CountryService.java
  src/main/java/com/depromeet/sulsul/domain/flavor/entity/Flavor.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Member.java
  src/main/java/com/depromeet/sulsul/domain/memberBeerFlavor/entity/MemberBeerFlavor.java
  src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordRequestDto.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/record/entity/Record.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/record/service/RecordService.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/dto/RecordFlavorRequest.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/entity/RecordFlavor.java
  src/main/java/com/depromeet/sulsul/domain/recordFlavor/service/RecordFlavorService.java
  src/main/java/com/depromeet/sulsul/util/ImageUtil.java
  src/main/java/com/depromeet/sulsul/util/PaginationUtil.java
  src/main/java/com/depromeet/sulsul/util/PropertyUtil.java
Labels: feat, chore, request a review

#50 :sparkles: 맥주 추천 리스트 조회 API 개발
  src/main/java/com/depromeet/sulsul/domain/beer/controller/BeerController.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerResponsesDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/beer/service/BeerService.java
  src/main/java/com/depromeet/sulsul/util/PaginationUtil.java
Labels: feat

#57 ✨ 맥주 상세보기 : 해당 맥주 맛 count 조회 기능 부여
  src/main/java/com/depromeet/sulsul/common/entity/BaseEntity.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerDetailResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/flavor/controller/FlavorController.java
  src/main/java/com/depromeet/sulsul/domain/flavor/dto/FlavorResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/flavor/repository/FlavorRepository.java
  src/main/java/com/depromeet/sulsul/domain/flavor/repository/FlavorRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/flavor/repository/FlavorRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/flavor/service/FlavorService.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/controller/MemberBeerController.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/entity/MemberBeer.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/repository/MemberBeerRepository.java
  src/main/java/com/depromeet/sulsul/domain/memberBeer/service/MemberBeerService.java
  src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustomImpl.java
Labels: feat, chore, request a review

#60 🎨 병합 오류 해결
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/beer/service/BeerService.java
  src/main/java/com/depromeet/sulsul/domain/flavor/controller/FlavorController.java
  src/main/java/com/depromeet/sulsul/domain/flavor/repository/FlavorRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustomImpl.java
Labels: chore
