Repository depromeet/sulsul-BE, pull requests merged in 2022-04, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#2 🎨 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#3 🎨 PR 템플릿 등록
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#6 보일러 플레이트 설정
  build.gradle
  src/main/java/com/depromeet/sulsul/SulsulApplication.java
  src/main/java/com/depromeet/sulsul/common/entity/BaseEntity.java
  src/main/java/com/depromeet/sulsul/common/error/GlobalExceptionHandler.java
  src/main/java/com/depromeet/sulsul/common/error/dto/ErrorCode.java
  src/main/java/com/depromeet/sulsul/common/error/dto/ErrorDto.java
  src/main/java/com/depromeet/sulsul/common/error/exception/BusinessException.java
  src/main/java/com/depromeet/sulsul/common/error/exception/custom/MemberNotFoundException.java
  src/main/java/com/depromeet/sulsul/common/response/dto/ResponseDto.java
  src/main/java/com/depromeet/sulsul/config/QuerydslConfig.java
  src/main/java/com/depromeet/sulsul/domain/member/controller/MemberController.java
  src/main/java/com/depromeet/sulsul/domain/member/dto/MemberDto.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Member.java
  src/main/java/com/depromeet/sulsul/domain/member/repository/MemberRepository.java
  src/main/java/com/depromeet/sulsul/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/member/repository/impl/MemberRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/member/service/MemberService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: chore

#8 🎨 예외 문구 클래스명 변경
  src/main/java/com/depromeet/sulsul/common/error/dto/ErrorType.java
  src/main/java/com/depromeet/sulsul/common/error/exception/custom/MemberNotFoundException.java
Labels: style

#14 Beer 전체 조회 기능(Pagination) 개발
  src/main/java/com/depromeet/sulsul/common/response/dto/PageableResponse.java
  src/main/java/com/depromeet/sulsul/domain/MemberBeer.java
  src/main/java/com/depromeet/sulsul/domain/beer/controller/BeerController.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerDto.java
  src/main/java/com/depromeet/sulsul/domain/beer/dto/BeerRequest.java
  src/main/java/com/depromeet/sulsul/domain/beer/entity/Beer.java
  src/main/java/com/depromeet/sulsul/domain/beer/entity/BeerType.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepository.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/beer/service/BeerService.java
  src/main/java/com/depromeet/sulsul/domain/continent/dto/ContinentDto.java
  src/main/java/com/depromeet/sulsul/domain/country/dto/CountryDto.java
  src/main/java/com/depromeet/sulsul/domain/country/repository/CountryRepository.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Beer.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/BeerFlavor.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/BeerType.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Continent.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Country.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Flavor.java
  src/main/java/com/depromeet/sulsul/domain/member/entity/Review.java
  src/main/java/com/depromeet/sulsul/util/PaginationUtil.java
  src/main/java/com/depromeet/sulsul/util/PropertyUtil.java
Labels: feat
