Repository depromeet/sulsul-BE, pull requests merged in 2022-06, with the labels that each got.

#72 :sparkles: 유저가 반한 맥주 리스트 조회 API 개발
  src/main/java/com/depromeet/sulsul/domain/beer/controller/BeerController.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/beer/repository/BeerRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/beer/service/BeerService.java
  src/main/java/com/depromeet/sulsul/domain/member/controller/MemberController.java
Labels: feat, request a review, refactor

#73 작성 맥주 리스트 관련 API 및 기존 기록조회 API 수정
  src/main/java/com/depromeet/sulsul/config/SecurityConfig.java
  src/main/java/com/depromeet/sulsul/domain/flavor/controller/FlavorController.java
  src/main/java/com/depromeet/sulsul/domain/record/controller/RecordController.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordCountryAndCountResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordFindRequestDto.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordTicketResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/record/entity/Record.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustom.java
  src/main/java/com/depromeet/sulsul/domain/record/repository/RecordRepositoryCustomImpl.java
  src/main/java/com/depromeet/sulsul/domain/record/service/RecordService.java
Labels: feat, chore, request a review, refactor

#77 :ambulance: dockerfile 수정 및 submodule 처리 수정
  .gitmodules
  Dockerfile
Labels: request a review, refactor

#253 🚑 국가 시작점 수정
  .github/workflows/prod.yml
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/record/entity/Record.java
  src/main/java/com/depromeet/sulsul/util/PropertyUtil.java
Labels: request a review, refactor, hotfix

#255 🚑 인증 관련 잘못된 요청 시 반환 데이터 통일 #251
  src/main/java/com/depromeet/sulsul/common/interceptor/AuthInterceptor.java
  src/main/java/com/depromeet/sulsul/domain/member/repository/MemberRepository.java
  src/main/java/com/depromeet/sulsul/domain/record/dto/RecordResponseDto.java
  src/main/java/com/depromeet/sulsul/domain/token/service/JwtTokenService.java
  src/main/java/com/depromeet/sulsul/oauth2/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/depromeet/sulsul/util/HttpResponseUtil.java
  src/main/resources/application.yml
Labels: bug, hotfix

#258 🚑 accessToken 만료시간 조정 및 인터셉터 이슈 조치
  src/main/java/com/depromeet/sulsul/common/interceptor/AuthInterceptor.java
  src/main/java/com/depromeet/sulsul/domain/member/repository/MemberRepository.java
  src/main/java/com/depromeet/sulsul/oauth2/provider/JwtTokenProvider.java
Labels: bug, hotfix
